name: deploy
on:
  push:
    branches:
      - stage
      - uat
      # - master
jobs:
#  build:
#    runs-on: ubuntu-20.04
#    steps:
#      - uses: actions/checkout@v2
  deployStage:
    name: deploy to stage
    if: github.event.ref == 'refs/heads/stage'
#    needs: [build]
    runs-on: ubuntu-20.04
    environment:
      name: stage
      url: 'https://example.com'
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
        with:
          php-version: 7.4
          extensions: mbstring, intl, pdo_sqlite, pdo_mysql
      - name: deploy
        run: cd deploy && php deployer.phar
  deployUat:
    name: deploy to uat
    if: github.event.ref == 'refs/heads/uat'
#    needs: [build]
    runs-on: ubuntu-20.04
    environment:
      name: uat
      url: 'https://example.com'
    steps:
      - name: deploy
        run: echo I am deploying!
  deployProd:
    name: deploy to prod
    if: github.event.ref == 'refs/heads/master'
#    needs: [build]
    runs-on: ubuntu-20.04
    environment:
      name: prod
      url: 'https://example.com'
    steps:
      - name: deploy
        run: echo I am deploying!

#            - name: remote deploy
#             uses: appleboy/ssh-action@master
#              with:
#                  host: ${{ secrets.HOST }}
#                  username: ${{ secrets.USERNAME }}
#                  key: ${{ secrets.KEY }}
#                  port: ${{ secrets.PORT }}
#                  script: XXX
